/* Generated with cbindgen:0.26.0 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

enum LitColorC {
  White,
  Black,
  Red,
  Green,
  Violet,
  Gold,
  Silver,
  Rose,
};

struct LitCelebrationC {
  /**
   * The key is unique among other celebrations, but if the celebration appears
   * on a different year, the key is the same
   */
  uint8_t event_key[128];
  int32_t rank;
  enum LitColorC color;
  uint8_t title[256];
  uint8_t subtitle[128];
  uint8_t gospel_ref[64];
  uint8_t *gospel_text;
  uint8_t *readings_url;
  uint8_t season[32];
  /**
   * seconds from 19700101 to 00:00 (midnight the morning of) on the day of this celebration
   */
  int64_t epoch_seconds;
};

int lit_celebrations_in_range_c(const char *db_path,
                                int cal_id,
                                long long lo,
                                long long hi,
                                struct LitCelebrationC **out_cels,
                                int *out_count);
