import "./globals.css"
import localFont from "next/font/local"

const euclid = localFont({ src: "./EuclidSquare-Regular.ttf" })

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({ children }) {
	return (
		<html lang="en" className="h-full bg-white">
			<body className={euclid.className + " h-full"}>{children}</body>
		</html>
	)
}
